apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider-kubernetes
  labels:
    core.crossplane.io/name: "provider-kubernetes"
spec:
  selector:
    matchLabels:
      core.crossplane.io/name: "provider-kubernetes"
  replicas: 1
  template:
    metadata:
      name: "provider-kubernetes-controller"
      labels:
        core.crossplane.io/name: "provider-kubernetes"
    spec:
      containers:
      - name: "provider-kubernetes-controller"
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: XDG_CACHE_HOME
          value: /tmp