apiVersion: v1
kind: Namespace
metadata:
  name: helm
---
apiVersion: packages.crossplane.io/v1alpha1
kind: ClusterPackageInstall
metadata:
  name: provider-kubernetes
  namespace: helm
spec:
  package: "provider-kubernetes:local"
  imagePullPolicy: Never